# Setup
title       : NP Packages
tagline     : 'NP Software Packages'
description : 'Nonparametric Software Packages'
keywords    : "nonparametric, semiparametric, smoothing, R, Stata"
url         : https://nppackages.github.io
baseurl     : ''
paginate    : 5


# About and contact
author:
  name:           
  url:            

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
